// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwnsvjljtlwmjyaqeyzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3bnN2amxqdGx3bWp5YXFleXprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NTI5OTUsImV4cCI6MjA2MTQyODk5NX0.FcpCID1-SkGkQyxmxmJ4ohTeBDNnb4H9gxxQbSxxR0w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);